{% set name = "datapungi_fed" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/datapungi_fed-{{ version }}.tar.gz
  sha256: f17d342099854d676bcfa2b8e52188ab284431e55aa8ee844062b165231ba10f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python
  run:
    - beautifulsoup4
    - html5lib
    - lxml
    - pandas
    - pyperclip
    - pytest
    - pytest-html
    - python
    - pyyaml
    - requests
    - xlrd

test:
  imports:
    - datapungi_fed
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jjotterson/datapungi_fed
  summary: Gets FRED and GeoFRED data from Federal Reserve (FED) by connecting to its API.
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - ADD_YOUR_GITHUB_ID_HERE
